---
version: '2.2'
services:
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    depends_on:
      - upstream
      - control-plane
    command:
      - /usr/local/bin/envoy
      - --config-path
      - /etc/envoy.yaml
      - --log-level
      - info
      - --component-log-level
      - wasm:debug
      - --service-cluster
      - proxy
    expose:
      - "8001" # admin
      - "9000" # traffic
    ports:
      - "8001:8001" # admin
      - "9000:9000" # traffic
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
      - ./target/request_buffer.wasm:/opt/wasm/request_buffer.wasm
  control-plane:
    build:
      dockerfile: control-plane/Containerfile
      context: .
    ports:
      - "7001:7001"
  upstream:
    build:
      dockerfile: upstream/Containerfile
      context: .
    ports:
      - "50001:50001" # http
      - "50002:50002" # grpc