FROM tinygo/tinygo:0.30.0 as build

WORKDIR /go/src/app
COPY . .

RUN go mod download

RUN tinygo build -o request_buffer_service.wasm -scheduler=none -target=wasi wasm-request-buffer/service/main.go

FROM scratch

COPY --from=build /go/src/app/request_buffer_service.wasm /plugin.wasm
