# istio does not yet allow a WasmPlugin to be a WasmService (singleton)
# so we also register this one as HTTP, but it does nothing on HTTPContext
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: request-buffer-service
  namespace: default
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: external-gateway
  url: oci://quay.io/rlehmann/envoy-request-buffer-wasm-service:latest
  imagePullPolicy: IfNotPresent
  type: HTTP
  phase: UNSPECIFIED_PHASE
  pluginConfig:
    control-plane-url: control-plane.default.svc.cluster.local
    control-plane-cluster: outbound|7001||control-plane.default.svc.cluster.local
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: request-buffer-filter
  namespace: default
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: external-gateway
  url: oci://quay.io/rlehmann/envoy-request-buffer-wasm-filter:latest
  imagePullPolicy: IfNotPresent
  type: HTTP
  phase: UNSPECIFIED_PHASE
  pluginConfig:
    control-plane-url: control-plane.default.svc.cluster.local
    control-plane-cluster: outbound|7001||control-plane.default.svc.cluster.local
